name: ci-workflow
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
   first_job:
    runs-on: ubuntu-lastest
    steps:
      - name: Welcome Step
        run: echo "welcometo github Actions"
      - name: Checkout Repositery
        uses: actions/checkout@v4
      - name: Repositery Basic Info
        run:  |
          echo "Repository Name: ${{github.repository}}"
          echo "Repository Owner: ${{github.owner}}"
          echo "Event Name: ${{github.event}}"
          